- name: Install docker
  yum: name={{ item }} state=present
  with_items:
  - docker
  - docker-python

- meta: flush_handlers

- name: Enable and start docker
  service: name=docker enabled=true state=started
